name: Python CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r modules/03_Python_Flask/requirements.txt
              continue-on-error: true

            - name: Run Flake Linting
              run: flake8 modules/03_Python_Flask/
              continue-on-error: true

            - name: Run Tests
              run: pytest modules/03_Python_Flask/test_app.py
              continue-on-error: true